=== LittleYe233/FuckHomework/schemas/locales.json
{
  "$schema": "http://json-schema.org/schema",
  "$id": "locales",
  "type": "object",
  "description": "Schema for locales. They are for i18next package.",
  "properties": {
    "heading": {
      "type": "object",
      "properties": {
        "homework": {
          "type": "object",
          "properties": {
            "submission": {
              "type": "string"
            },
            "list": {
              "type": "string"
            }
          }
        },
        "control_pad": {
          "type": "string"
        },
        "components": {
          "type": "object",
          "properties": {
            "homework_slot": {
              "type": "object",
              "properties": {
                "semester": {
                  "type": "string"
                },
                "subject": {
                  "type": "string"
                },
                "chapter": {
                  "type": "string"
                },
                "due_time": {
                  "type": "string"
                },
                "submission_method": {
                  "type": "string"
                }
              }
            },
            "homework_upload": {
              "type": "object",
              "properties": {
                "upload_homework": {
                  "type": "string"
                },
                "result": {
                  "type": "string"
                },
                "output_nerd": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "message": {
      "type": "object",
      "properties": {
        "homework": {
          "type": "object",
          "properties": {
            "subfolder_is_file": {
              "type": "string"
            },
            "upload": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "object",
                  "properties": {
                    "failed": {
                      "type": "string"
                    },
                    "passed": {
                      "type": "string"
                    }
                  }
                },
                "no_input": {
                  "type": "string"
                },
                "no_input_nerd": {
                  "type": "string"
                },
                "no_uploaded_nerd": {
                  "type": "string"
                },
                "failed_some": {
                  "type": "string"
                },
                "failed_all": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "control": {
      "type": "object",
      "properties": {
        "homepage": {
          "type": "string"
        }
      }
    },
    "error": {
      "type": "object",
      "properties": {
        "invalid_version": {
          "type": "string"
        },
        "homework_no_title": {
          "type": "string"
        },
        "invalid_date": {
          "type": "string"
        }
      }
    },
    "variable": {
      "type": "object",
      "properties": {
        "homework": {
          "type": "object",
          "properties": {
            "default": {
              "type": "object",
              "properties": {
                "submission_method": {
                  "type": "string"
                }
              }
            },
            "substitution": {
              "type": "object",
              "properties": {
                "homework": {
                  "type": "object",
                  "properties": {
                    "title": {
                      "type": "string"
                    },
                    "semester": {
                      "type": "string"
                    },
                    "subject": {
                      "type": "string"
                    },
                    "chapter": {
                      "type": "string"
                    }
                  }
                },
                "student": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "rule": {
      "type": "object",
      "properties": {
        "error": {
          "type": "object",
          "properties": {
            "invalid_type": {
              "type": "string"
            },
            "invalid_pattern_type": {
              "type": "string"
            }
          }
        },
        "filename_check": {
          "type": "object",
          "properties": {
            "message": {
              "type": "object",
              "properties": {
                "filename_invalid": {
                  "type": "string"
                },
                "filename_no_valid": {
                  "type": "string"
                }
              }
            },
            "output": {
              "type": "object",
              "properties": {
                "regexp_pattern": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  }
}

=== LittleYe233/FuckHomework/locales/zh.json
{
  "heading": {
    "homework": {
      "submission": "作业上传",
      "list": "作业列表"
    },
    "control_pad": "控制面板",
    "components": {
      "homework_slot": {
        "semester": "学期",
        "subject": "课程",
        "chapter": "章节",
        "due_time": "截止时间",
        "submission_method": "提交方式"
      },
      "homework_upload": {
        "upload_homework": "上传作业",
        "result": "结果",
        "output_nerd": "调试输出"
      }
    }
  },
  "message": {
    "homework": {
      "subfolder_is_file": "作业文件夹指定路径不是文件夹：{{- subFolderFullPath}}",
      "upload": {
        "status": {
          "failed": "失败",
          "passed": "成功"
        },
        "no_input": "没有输入文件",
        "no_input_nerd": "错误：没有输入文件。",
        "no_uploaded_nerd": "没有文件被上传。",
        "failed_some": "部分文件上传失败",
        "failed_all": "所有文件上传失败"
      }
    }
  },
  "control": {
    "homepage": "返回主页"
  },
  "error": {
    "invalid_version": "无效的版本号：{{version}}",
    "homework_no_title": "作业无标题",
    "invalid_date": "无效的日期"
  },
  "variable": {
    "homework": {
      "default": {
        "submission_method": "上传文件"
      },
      "substitution": {
        "homework": {
          "title": "标题",
          "semester": "学期",
          "subject": "课程",
          "chapter": "章节"
        },
        "student": {
          "id": "学号",
          "name": "学生姓名"
        }
      }
    }
  },
  "rule": {
    "error": {
      "invalid_type": "无效的规则类型：{{type}}",
      "invalid_pattern_type": "无效的模式类型"
    },
    "filename_check": {
      "message": {
        "filename_no_valid": "文件名未命中任何白名单规则",
        "filename_invalid": "文件名命中某黑名单规则"
      },
      "output": {
        "regexp_pattern": "正则表达式：<code>{{- pattern}}</code>"
      }
    }
  }
}

=== LittleYe233/FuckHomework/locales/en.json
{
  "heading": {
    "homework": {
      "submission": "Homework Submission",
      "list": "Homework list"
    },
    "control_pad": "Control Pad"
  },
  "message": {
    "homework": {
      "subfolder_is_file": "homework subfolder path exists but is not a directory: {{- subFolderFullPath}}",
      "upload": {
        "status": {
          "failed": "Failed",
          "passed": "Passed"
        },
        "no_input": "No input files",
        "no_input_nerd": "Error: No input files.",
        "no_uploaded_nerd": "No files are uploaded.",
        "failed_some": "Failed to upload some files",
        "failed_all": "Failed to upload all files"
      }
    }
  },
  "control": {
    "homepage": "Back to homepage"
  },
  "error": {
    "invalid_version": "invalid version number: {{version}}",
    "homework_no_title": "assignment has no title",
    "invalid_date": "invalid date"
  },
  "variable": {
    "homework": {
      "default": {
        "submission_method": "Uploading files"
      },
      "substitution": {
        "homework": {
          "title": "title",
          "semester": "semester",
          "subject": "subject",
          "chapter": "chapter"
        },
        "student": {
          "id": "student id",
          "name": "student name"
        }
      }
    }
  },
  "rule": {
    "error": {
      "invalid_type": "invalid type name of rule: {{type}}",
      "invalid_pattern_type": "invalid pattern type"
    },
    "filename_check": {
      "message": {
        "filename_no_valid": "Filename does not meet any of valid patterns",
        "filename_invalid": "Filename meets certain invalid pattern"
      },
      "output": {
        "regexp_pattern": "RegExp: <code>{{- pattern}}</code>"
      }
    }
  }
}
